# -*- coding: utf-8 -*-
"""Set_3_Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEumaOIT9m3_wDmSvdKubVNV81jFQye6
"""

"""
10. Average of intergers
    - User input integer N>1
    - Program computes the average integers
    - Print result
"""

num=int(input("Enter an integer greater than 1"))

total = 0
for i in range(1, num + 1):
  total += i
avg = total / num

if num <= 1:
    print("Enter an integer greater than 1")
else:
    print("The average of integers 1 to", num, "is", avg)

"""
11. A while loop with errors
    - the 'While' should be 'while'
    - "While i < 11" statement should include ':'
    - "print some_number" wrong variable instead of 'Some_number' - print statement doesn't have (brackets)
"""

Some_number = 0
i = 1

while i < 11:
  Some_number += i
  i += 1
print(Some_number)